application: leaguedata
version: 2
runtime: python
api_version: 1

handlers:

- url: /style.css
  static_files: files/style/builder.css
  upload: files/style/builder.css

- url: /results
  script: results.py
  
- url: /standings
  script: standings.py

- url: /files
  static_dir: files

- url: /example
  static_dir: files/example

- url: /favicon.ico
  static_files: files/images/favicon.ico
  upload: files/images/favicon.ico
  
- url: /edit
  script: start.py
  
- url: /import
  script: importer.py
  
- url: /tables
  script: first.py

- url: .*
  script: start.py
