application: tabled
version: 1
runtime: python
api_version: 1

handlers:

- url: /sample.xls
  static_files: files/samples/sample.xls
  upload: files/samples/sample.xls

- url: /style.css
  static_files: files/style/builder.css
  upload: files/style/builder.css

- url: /results
  script: results.py
  
- url: /standings
  script: standings.py

- url: /league.jpg
  static_files: files/images/league.jpg
  upload: files/images/league.jpg

- url: /files
  static_dir: files

- url: /example
  static_dir: files/example

- url: /favicon.ico
  static_files: files/images/favicon.ico
  upload: files/images/favicon.ico
  
- url: /import
  script: importer.py

- url: .*
  script: start.py
